const router = require("express").Router()
const formData = require("express-form-data")
const decentralize_service = require("../../controllers/Role/Decentralize")
const func = require("../../services/function")
router.post("/create-decentralize", formData.parse(), func.checkToken, decentralize_service.createRole)
router.post("/update-decentralize", formData.parse(), func.checkToken, decentralize_service.updateDecentralize)
router.post("/delete-decentralize", formData.parse(), func.checkToken, decentralize_service.deletedentralize)
router.get("/list-decentralize", formData.parse(), func.checkToken, decentralize_service.listDecentralize)
router.post("/detail-decentralize", formData.parse(), func.checkToken, decentralize_service.detailDecentralizes)
module.exports = router;