const router = require("express").Router()
const formData = require("express-form-data")
const decentralize_controller = require("../../controllers/Role/Decentralize")
const func = require("../../services/function")
router.post("/create-decentralize", formData.parse(), func.checkToken, decentralize_controller.createRole)
router.post("/update-decentralize", formData.parse(), func.checkToken, decentralize_controller.updateDecentralize)
router.post("/delete-decentralize", formData.parse(), func.checkToken, decentralize_controller.deletedentralize)
router.get("/list-decentralize", formData.parse(), func.checkToken, decentralize_controller.listDecentralize)
router.post("/detail-decentralize", formData.parse(), func.checkToken, decentralize_controller.detailDecentralizes)
module.exports = router;